# Generated by Django 4.2.30 on 2026-09-22 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0006_appointment_assigned_mechanic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='service_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
