# Generated by Django 4.2.30 on 2026-09-30 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


def mark_legacy_payments_unverified(apps, schema_editor):
    Invoice = apps.get_model('workshop', 'Invoice')
    Invoice.objects.filter(payment_status__in=['paid', 'partial']).update(payment_status='unverified')


def restore_legacy_statuses_as_unpaid(apps, schema_editor):
    Invoice = apps.get_model('workshop', 'Invoice')
    Invoice.objects.filter(payment_status='unverified').update(payment_status='unpaid')


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workshop', '0008_repairorder_pending_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('partial', 'Partially Paid'), ('paid', 'Paid'), ('unverified', 'Needs Verification')], default='unpaid', max_length=10),
        ),
        migrations.CreateModel(
            name='InvoicePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('eft', 'EFT'), ('other', 'Other')], max_length=10)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='workshop.invoice')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_invoice_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-received_at', '-pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='invoicepayment',
            constraint=models.CheckConstraint(check=models.Q(('amount__gt', 0)), name='invoice_payment_amount_positive'),
        ),
        migrations.RunPython(mark_legacy_payments_unverified, restore_legacy_statuses_as_unpaid),
    ]
