# Generated by Django 4.2.30 on 2026-10-01 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workshop', '0011_repairorderevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collected_at', models.DateTimeField(auto_now_add=True)),
                ('handover_note', models.TextField(blank=True)),
                ('collected_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_collections', to=settings.AUTH_USER_MODEL)),
                ('repair_order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='collection_record', to='workshop.repairorder')),
            ],
        ),
    ]
