# Generated by Django 4.2.30 on 2026-10-01 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0017_repairestimateline_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(check=models.Q(('service_amount__gte', 0)), name='invoice_service_amount_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(check=models.Q(('discount__gte', 0)), name='invoice_discount_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(check=models.Q(('discount__lte', models.F('service_amount'))), name='invoice_discount_within_service_amount'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(check=models.Q(('tax_rate__gte', 0)), name='invoice_tax_rate_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(check=models.Q(('due_date__gte', models.F('issue_date'))), name='invoice_due_date_not_before_issue'),
        ),
        migrations.AddConstraint(
            model_name='laborline',
            constraint=models.CheckConstraint(check=models.Q(('hours__gt', 0)), name='labor_line_hours_positive'),
        ),
        migrations.AddConstraint(
            model_name='laborline',
            constraint=models.CheckConstraint(check=models.Q(('rate__gte', 0)), name='labor_line_rate_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='part',
            constraint=models.CheckConstraint(check=models.Q(('cost_price__gte', 0)), name='part_cost_price_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='part',
            constraint=models.CheckConstraint(check=models.Q(('sell_price__gte', 0)), name='part_sell_price_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='partsline',
            constraint=models.CheckConstraint(check=models.Q(('quantity__gt', 0)), name='parts_line_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='partsline',
            constraint=models.CheckConstraint(check=models.Q(('unit_price__gte', 0)), name='parts_line_price_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='serviceitem',
            constraint=models.CheckConstraint(check=models.Q(('labor_hours__gte', 0)), name='service_labor_hours_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='serviceitem',
            constraint=models.CheckConstraint(check=models.Q(('labor_rate__gte', 0)), name='service_labor_rate_nonnegative'),
        ),
    ]
