# Generated by Django 4.2.30 on 2026-10-01 16:52

from django.db import migrations, models


def normalize_estimate_line_references(apps, schema_editor):
    estimate_line = apps.get_model('workshop', 'RepairEstimateLine')
    database = schema_editor.connection.alias
    lines = estimate_line.objects.using(database)
    lines.filter(
        line_type='labor',
        service_item__isnull=False,
        part__isnull=False,
    ).update(part=None)
    lines.filter(
        line_type='part',
        service_item__isnull=False,
        part__isnull=False,
    ).update(service_item=None)

    invalid_lines = lines.exclude(
        models.Q(line_type='labor', service_item__isnull=False, part__isnull=True)
        | models.Q(line_type='part', service_item__isnull=True, part__isnull=False)
    )
    if invalid_lines.exists():
        invalid_ids = list(invalid_lines.values_list('pk', flat=True)[:20])
        raise RuntimeError(
            'Estimate lines still need manual reconciliation before enforcing '
            f'type/reference integrity. Example IDs: {invalid_ids}'
        )


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0018_enforce_business_rules'),
    ]

    operations = [
        migrations.RunPython(normalize_estimate_line_references, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='repairestimateline',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('line_type', 'labor'), ('part__isnull', True), ('service_item__isnull', False)), models.Q(('line_type', 'part'), ('part__isnull', False), ('service_item__isnull', True)), _connector='OR'), name='estimate_line_item_matches_type'),
        ),
    ]
