# Generated by Django 4.2.30 on 2026-10-09 12:35

from decimal import Decimal
from django.db import migrations, models


def normalize_invoice_vat(apps, schema_editor):
    Invoice = apps.get_model('workshop', 'Invoice')
    Invoice.objects.exclude(tax_rate=Decimal('15.00')).update(tax_rate=Decimal('15.00'))


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0020_protect_audit_references'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='invoice',
            name='invoice_tax_rate_nonnegative',
        ),
        migrations.AddField(
            model_name='appointment',
            name='assignment_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('15.00'), editable=False, max_digits=5),
        ),
        migrations.AlterField(
            model_name='repairorderevent',
            name='event_type',
            field=models.CharField(choices=[('created', 'Repair order created'), ('assignment', 'Mechanic assignment changed'), ('status_proposed', 'Status proposed'), ('status_changed', 'Status changed'), ('status_rejected', 'Status update rejected'), ('approval', 'Customer approval recorded'), ('payment', 'Payment recorded'), ('work_logged', 'Repair work logged'), ('cancelled', 'Repair order cancelled'), ('collected', 'Vehicle collected')], max_length=30),
        ),
        migrations.RunPython(normalize_invoice_vat),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(check=models.Q(('tax_rate', Decimal('15.00'))), name='invoice_vat_fixed_at_15'),
        ),
    ]
