# Generated by Django 4.2.30 on 2026-10-09 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0021_audit_log_immutability_triggers'),
        ('workshop', '0021_remove_invoice_invoice_tax_rate_nonnegative_and_more'),
    ]

    operations = [
    ]
